<?php

namespace Cps\chequeBundle\Repository;

/**
 * accesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class accesoRepository extends \Doctrine\ORM\EntityRepository
{
}
