<?php

namespace Cps\chequeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * benficiarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class benficiarioRepository extends EntityRepository
{
    public function findAjaxValue($term){
        return $this->getEntityManager()
        ->createQuery(
            'SELECT p FROM CpschequeBundle:benficiario p WHERE p.nombre LIKE :value')
            ->setParameter('value','%'.$term.'%')
            ->getResult();
    }
    public function BeneficiarioSearch($searchQuery){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT c
                                     FROM CpschequeBundle:Benficiario c
                                     where c.nombre LIKE '%$searchQuery%' ORDER BY c.id");
        $result = $query->getResult();
        return $result;
    }
}
