<?php

namespace Cps\chequeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * chequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chequeRepository extends EntityRepository
{
    public function ChequeSearch($usuario, $searchQuery){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT o.id, c.bte , o.cheque, o.monto, b.nombre, o.estado, c.id as proId
                                     FROM CpschequeBundle:Comprobante c
                                     JOIN c.cheque o
                                     JOIN o.benficiario b
                                     where c.activo = 1 and o.estado <> 3 and o.cheque LIKE '%$searchQuery%' and c.Usuario=:nro ORDER BY c.id DESC")
                ->setParameter("nro",$usuario);
        $result = $query->getResult();
        return $result;
    }
    public function aChequeSearch($usuario, $searchQuery){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT o.id, o.cheque, o.monto, b.nombre, o.estado,c.id as proId
                                     FROM CpschequeBundle:Comprobante c
                                     JOIN c.cheque o
                                     JOIN o.benficiario b
                                     where c.activo = 1 and o.estado = 3 and o.cheque LIKE '%$searchQuery%' and c.Usuario=:nro ORDER BY c.id DESC")
                ->setParameter("nro",$usuario);
        $result = $query->getResult();
        return $result;
    }
    public function rChequeSearch($searchQuery){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT o.id, o.cheque, o.monto, b.nombre, o.estado
                                     FROM CpschequeBundle:Comprobante c
                                     JOIN c.cheque o
                                     JOIN o.benficiario b
                                     where c.activo = 1 and o.cheque LIKE '%$searchQuery%' ORDER BY c.id DESC");
        $result = $query->getResult();
        return $result;
    }
    public function rCheque($searchQuery){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT o.id, o.cheque, o.monto, b.nombre, o.estado, c.id as proId
                                     FROM CpschequeBundle:Comprobante c
                                     JOIN c.cheque o
                                     JOIN o.benficiario b
                                     where c.activo = 1 and o.cheque LIKE '%$searchQuery%' and o.estado = 4 ORDER BY c.id DESC");
        $result = $query->getResult();
        return $result;
    }
    public function BuscarPorId($comprobanteId){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT c
                                 FROM CpschequeBundle:cheque c
                                 WHERE c.activo = 1 and c.comprobante = :nro  ORDER BY c.id desc")
                                 ->setParameter("nro",$comprobanteId);
        $result = $query->getResult();
        return $result;
    }
    public function verificar($chequeData){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT c
                                 FROM CpschequeBundle:cheque c
                                 WHERE c.activo = 1 and c.cheque = :nro")
                                 ->setParameter("nro",$chequeData);
        $result = $query->getResult();
        return $result;
    }
    public function obtenerfechaCheque($nroCheque){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT c.fecha
                                     FROM CpschequeBundle:Comprobante c
                                     JOIN c.cheque o
                                     where c.activo = 1 and o.cheque = :nrocheque ")
                                     ->setParameter(':nrocheque', $nroCheque);
        $result = $query->getResult();
        return $result;
    }

    public function reportegeneral($fini,$ffin){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT c.fecha, c.glosa, b.nombre, o.cheque, c.docres, c.bte, o.monto, o.estado
                                     FROM CpschequeBundle:Comprobante c
                                     JOIN c.cheque o
                                     JOIN o.benficiario b
                                     WHERE c.activo = 1 and o.activo = 1 and c.fecha BETWEEN :ini and :fin ORDER BY c.fecha ASC")
                                     ->setParameter(':ini', $fini)
                                     ->setParameter(':fin', $ffin);
        $result = $query->getResult();
        return $result;
    }

    //reporte de cheque por usuario
    public function reportePorUsuario($fini,$ffin,$usuario){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT c.fecha, c.glosa, b.nombre, o.cheque, c.docres, c.bte, o.monto, o.estado, c.id as proId
                                     FROM CpschequeBundle:Comprobante c
                                     JOIN c.cheque o
                                     JOIN o.benficiario b
                                     WHERE c.activo = 1 and o.activo = 1 and  c.fecha BETWEEN :ini and :fin and c.Usuario = :usu ORDER BY c.fecha ASC ")
                                     ->setParameter(':ini', $fini)
                                     ->setParameter(':fin', $ffin)
                                     ->setParameter(':usu', $usuario);
        $result = $query->getResult();
        return $result;
    }
    public function buscarNombre($nombrebus){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT o.id as chequeId ,c.id as comprobanteId,c.fecha, c.glosa, b.nombre, o.cheque, c.docres, c.bte, o.monto, o.estado
                                     FROM CpschequeBundle:Comprobante c
                                     JOIN c.cheque o
                                     JOIN o.benficiario b
                                     WHERE c.activo = 1 and o.activo = 1 and b.nombre LIKE '%$nombrebus%' ORDER BY c.id DESC");
        $result = $query->getResult();
        return $result;
    }
    public function buscarNombreNro($nombrebusnro){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT c.fecha, c.glosa, b.nombre, o.cheque, c.docres, c.bte, o.monto, o.estado
                                     FROM CpschequeBundle:Comprobante c
                                     JOIN c.cheque o
                                     JOIN o.benficiario b
                                     WHERE c.activo = 1 and o.activo = 1 and o.cheque LIKE '%$nombrebusnro%' ORDER BY c.id DESC");
        $result = $query->getResult();
        return $result;
    }
}
