<?php

namespace Cps\chequeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * comprobanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class comprobanteRepository extends EntityRepository
{
    public function GCheque($proId){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT  d
                                  FROM CpschequeBundle:cheque d
                                  WHERE d.activo = 1 and d.comprobante= :nro ORDER BY d.id DESC")
            ->setParameter("nro", $proId);
        $result = $query->getResult();
        return $result;
    }

    public function ComprobanteSearch($usuario, $searchQuery){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT c
                                     FROM CpschequeBundle:Comprobante c
                                     where c.activo = 1 and c.bte LIKE '%$searchQuery%' and c.Usuario=:nro ORDER BY c.id DESC")
                ->setParameter("nro",$usuario);
        $result = $query->getResult();
        return $result;
    }
    public function verificar($bteData){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT c
                                 FROM CpschequeBundle:comprobante c
                                 WHERE c.activo = 1 and c.bte = :nro")
                                 ->setParameter("nro",$bteData);
        $result = $query->getResult();
        return $result;
    }
    public function datoExcel($fini,$ffin){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT c.fecha, c.glosa, b.nombre, o.cheque, c.docres, c.bte, o.monto, o.estado
                                     FROM CpschequeBundle:Comprobante c 
                                     JOIN c.cheque o
                                     JOIN o.benficiario b  
                                     WHERE c.activo = 1 and o.activo = 1 and c.fecha BETWEEN :fini and :ffin ORDER BY c.fecha ASC")
                                     ->setParameter('fini',$fini)
                                     ->setParameter('ffin',$ffin);
        $result = $query->getResult();
        return $result;
    }
    public function findAjaxValue($term){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM CpschequeBundle:comprobante p WHERE p.activo = 1 and p.bte LIKE :value')
            ->setParameter('value','%'.$term.'%')
            ->getResult();
    }
}
