<?php

namespace Cps\chequeBundle\Repository;

/**
 * entregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entregaRepository extends \Doctrine\ORM\EntityRepository
{
    public function reqEntregados(){
        $emp=$this->getEntityManager();
        $query = $emp->createQuery("SELECT e
                                     FROM CpschequeBundle:entrega e
                                     JOIN e.cheque c
                                     JOIN c.benficiario b
                                     WHERE  e.esActivo = 1 ORDER BY e.id DESC");

        $result = $query->getResult();
        return $result;
    }
}
