<?php

namespace Cps\chequeBundle\Repository;

/**
 * permisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class permisoRepository extends \Doctrine\ORM\EntityRepository
{
}
